name: Run native automated end-to-end tests for Android

on:
    workflow_dispatch:

    pull_request:
        branches: [master]

jobs:
    native_automated_tests_android:
        name: "Native automated tests for Android"
        runs-on: macos-latest
        permissions:
            packages: read
            contents: read
        steps:
            - name: "Checking-out code"
              uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
              with:
                  submodules: false
            - name: "Fetching master to compare"
              if: github.event_name == 'pull_request'
              run:
                  git fetch --no-tags --prune --depth=1 origin +refs/heads/${{ github.base_ref
                  }}:refs/remotes/origin/${{ github.base_ref }}
            - name: "Defining cache"
              uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2
              env:
                  cache-name: cache-node-modules
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
            - name: "Defining node version"
              uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
              with:
                  node-version: "16"
            - name: Install docker
              uses: docker-practice/actions-setup-docker@51fd5009666ea5e3382fe125abf5d73d31386b59
            - name: Login to GitHub Container Registry
              uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7 # v1.12.0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: "Use specific Java version for sdkmanager to work"
              uses: joschi/setup-jdk@v1
              with:
                  java-version: "openjdk8"
                  architecture: "x64"
              env:
                  # https://github.com/actions/toolkit/issues/641#issuecomment-728963957
                  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
            - name: "Installing dependencies"
              run: npm install
            - name: "Start Mendix Environment"
              id: start_mendix_environment
              run: npm run start:native-tests-ci && echo "::set-output name=CHANGED_PACKAGES::$CHANGED_PACKAGES"
              env:
                  CI: true
            - name: Setup emulator & run tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: 30
                  target: google_apis
                  arch: x86_64
                  profile: pixel
                  avd-name: NATIVE_pixel_30
                  script:
                      npx lerna run test:e2e:local:android --stream --concurrency 1 --scope ${{ steps.start_mendix_environment.CHANGED_PACKAGES }}
            - name: "Archive test screenshot diff results"
              uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
              if: failure()
              with:
                  name: test-screenshot-results
                  path: |
                      ${{ github.workspace }}/packages/**/e2e/images/diffs/**/*.png
                  if-no-files-found: error
