name: Run native automated end-to-end tests for Android
# todo: run different android emulators -> android version and devices
on:
    workflow_dispatch:

    push:
        branches: [master]

    pull_request:
        branches: [master]

jobs:
    native_automated_tests_android:
        name: "Native automated tests for Android"
        runs-on: macos-latest
        permissions:
            packages: read
            contents: read
        steps:
            - name: "What triggered this?"
              id: trigger
              run: echo "::set-output name=trigger::(if ${{ github.event_name == 'pull_request' }} && ${{ github.event.pull_request.head.repo.full_name == github.repository }}; then echo 'internal-pull-request';
                  elif ${{ github.event_name == 'pull_request' }} && ${{ github.event.pull_request.head.repo.full_name != github.repository }}; then echo 'external-pull-request';
                  else echo 'master'; fi)"
            - name: "Checking-out code"
              uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
              with:
                  submodules: false
            - name: "Fetching master to compare"
              if: github.event_name == 'pull_request'
              run:
                  git fetch --no-tags --prune --depth=1 origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
            - name: "Defining cache"
              uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2
              env:
                  cache-name: cache-node-modules
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
            - name: "Defining node version"
              uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
              with:
                  node-version: "16"
            - name: Install docker
              uses: docker-practice/actions-setup-docker@51fd5009666ea5e3382fe125abf5d73d31386b59
            - name: Login to GitHub Container Registry
              uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7 # v1.12.0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: "Use specific Java version for sdkmanager to work"
              uses: joschi/setup-jdk@f37b3738b0689ff2096f2cd914d631bcdeea7cf7
              with:
                  java-version: "openjdk8"
                  architecture: "x64"
              env:
                  # https://github.com/actions/toolkit/issues/641#issuecomment-728963957
                  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
            - name: "Installing dependencies"
              run: npm install
            - name: "Set changed packages"
              id: set-changed-packages
              run: node .github/scripts/set-changed-packages.js *-native
              env:
                  TRIGGER: ${{ steps.trigger.outputs.trigger }}
            - name: "Start Mendix Environment"
              id: start_mendix_environment
              run: npm run start:native-tests-ci
              env:
                  CHANGED_PACKAGES: ${{ steps.set-changed-packages.outputs.CHANGED_PACKAGES }}
                  CHANGED_PACKAGES_FORMATTED_FOR_LERNA: ${{ steps.set-changed-packages.outputs.CHANGED_PACKAGES_FORMATTED_FOR_LERNA }}
                  CI: true
            - name: Setup emulator & run tests
              uses: reactivecircus/android-emulator-runner@76c2bf6f95ed6458fd659a1bdb680a0f8df232dc
              with:
                  api-level: 30
                  target: google_apis
                  arch: x86_64
                  profile: pixel
                  avd-name: NATIVE_pixel_30
                  emulator-options: -skin 1080x1920
                  script:
                      npx lerna run test:e2e:local:android --stream --concurrency 1 --scope ${{ steps.set-changed-packages.outputs.CHANGED_PACKAGES_FORMATTED_FOR_LERNA }}
            - name: "Archive test screenshot diff results"
              uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
              if: failure()
              with:
                  name: test-screenshot-results
                  path: |
                      ${{ github.workspace }}/packages/**/e2e/images/**/*.png
                  if-no-files-found: error
