name: Run native automated end-to-end tests for Android
on:
  workflow_dispatch:

  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  project:
    runs-on: ubuntu-22.04
    container: ghcr.io/mendix/widgets-resources/mxbuild:9.13.0.43286
    steps:
      - name: Download test project
        run: curl -L -o project.zip https://github.com/mendix/Native-Mobile-Resources/archive/refs/heads/main.zip
      - name: Extract test project
        uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28
        with:
          args: unzip -qq project.zip
      - name: update-widgets
        run: mx update-widgets --loose-version-check Native-Mobile-Resources-main/NativeComponentsTestProject.mpr
      - name: Build test project
        run: mxbuild -o automation.mda Native-Mobile-Resources-main/NativeComponentsTestProject.mpr
      - name: Upload MDA
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
        with:
          name: mda
          path: automation.mda
  bundle:
    needs: project
    runs-on: ubuntu-22.04
    container: ghcr.io/mendix/widgets-resources/mxbuild:9.13.0.43286
    strategy:
      matrix:
        platform: [ 'android', 'ios' ]
    steps:
      - name: Download test project
        run: curl -L -o project.zip https://github.com/mendix/Native-Mobile-Resources/archive/refs/heads/main.zip
      - name: Extract test project
        uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28
        with:
          args: unzip -qq project.zip
      - uses: actions/download-artifact@master
        with:
          name: mda
      - name: Extract test project
        uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28
        with:
          args: unzip -qq automation.mda -d Native-Mobile-Resources-main/deployment
      - run: mkdir -p ${{ matrix.platform }}/assets
      - name: Bundle ${{ matrix.platform }}
        run: |
          cd Native-Mobile-Resources-main/deployment/native && \
          NODE_OPTIONS="--max-old-space-size=6144" /tmp/mxbuild/modeler/tools/node/node \
          /tmp/mxbuild/modeler/tools/node/node_modules/react-native/local-cli/cli.js \
          bundle --verbose --platform ${{ matrix.platform }} --dev false \
          --config "$PWD/metro.config.json" \
          --bundle-output $GITHUB_WORKSPACE/${{ matrix.platform }}/${{ matrix.platform }}.bundle \
          --assets-dest $GITHUB_WORKSPACE/${{ matrix.platform }}/assets/ \
          --entry-file ./index.js
      - name: Upload ${{ matrix.platform }} bundle
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
        with:
          name: ${{ matrix.platform }}
          path: ${{ matrix.platform }}
