name: Run native automated end-to-end tests for Android

on:
    workflow_dispatch:

    pull_request:
        branches: [master]

jobs:
    native_automated_tests_android:
        name: "Native automated tests for Android"
        runs-on: macos-latest
        permissions:
            packages: read
            contents: read
        steps:
            - name: "Checking-out code"
              uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
              with:
                  submodules: false
            - name: "Fetching master to compare"
              if: github.event_name == 'pull_request'
              run:
                  git fetch --no-tags --prune --depth=1 origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
            - name: "Defining cache"
              uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2
              env:
                  cache-name: cache-node-modules
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
            - name: "Defining node version"
              uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
              with:
                  node-version: "16"
            - name: Install podman
              run: |
                brew install fuse-overlayfs
                brew install podman
                podman machine init -v .:/mnt/widgets-resources
                podman machine start
            - name: Login to GitHub Container Registry
              run: podman login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
            - name: "Use specific Java version for sdkmanager to work"
              uses: joschi/setup-jdk@f37b3738b0689ff2096f2cd914d631bcdeea7cf7
              with:
                  java-version: "openjdk8"
                  architecture: "x64"
              env:
                  # https://github.com/actions/toolkit/issues/641#issuecomment-728963957
                  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
            - name: "Installing dependencies"
              run: npm install
            - name: "Set changed packages"
              id: set-changed-packages
              run: node .github/scripts/set-changed-packages.js *-native
            - name: "Start Mendix Environment"
              id: start_mendix_environment
              run: npm run start:native-tests-ci
              env:
                  CHANGED_PACKAGES: ${{ steps.set-changed-packages.outputs.CHANGED_PACKAGES }}
                  CI: true
            - name: Setup emulator & run tests
              uses: reactivecircus/android-emulator-runner@76c2bf6f95ed6458fd659a1bdb680a0f8df232dc
              with:
                  api-level: 30
                  target: google_apis
                  arch: x86_64
                  profile: pixel
                  avd-name: NATIVE_pixel_30
                  script:
                      npx lerna run test:e2e:local:android --stream --concurrency 1 --scope ${{ steps.set-changed-packages.outputs.CHANGED_PACKAGES }}
            - name: "Archive test screenshot diff results"
              uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
              if: failure()
              with:
                  name: test-screenshot-results
                  path: |
                      ${{ github.workspace }}/packages/**/e2e/images/diffs/**/*.png
                  if-no-files-found: error
